### ISSUE TITLE
No matching parser found via command line

### ISSUE THREAD

**Issue by Bernadette-Mohr** [FAIRmat-NFDI/hackathon-fair-spectroscopy-data-2024#1]
Following the instructions until `Matching the files to a parser`, I can call the new parser via a jupyter notebook as shown in the example.
Parsing via the command line fails:
```
nomad parse tests/data/trajectory.gsd
AssertionError: there is no parser matching trajectory.gsd
```
What other steps do I need to include?

**Comment by JosePizarro3** [comment]
🤔 did you modify the `src/nomad_parser_gsd/parsers/__init__.py` class to match your specific file? Or better question: do you have a branch I can take a look?

Today I am out, but on Mon I will check.

Thanks for the testing btw 🫠

**Comment by JosePizarro3** [comment]
Ok, I saw your latest branch in `main`, and I saw that you added `mainfile_contents_re`. This is for ASCII text files, but the `trajectory.gsd` seems to be a binary file, so you only need to use `mainfile_binary_header_re` instead 🙂

**Comment by Bernadette-Mohr** [comment]
Thank you, that solved it!
